### ISSUE TITLE
[Suggestion] Fuzzy version matching

### ISSUE THREAD

**Issue by osmarks** [dizzyd/mcdex#13]
I'm trying to create a 1.12.2 pack, but many mods are for 1.12 instead of 1.12.2. Since most 1.12 mods will probably work on 1.12.2, I'd like a way to ignore the .2 on the end when selecting a version.

**Comment by dizzyd** [comment]
I've released 0.7.4 that supports a primitive form of this fallback. For example if a 1.12.2 version of mod can't be found, it also looks for a 1.12 version. I'm considering changing it to actually walk all possible versions from (e.g. 1.12.2->1.12.1->1.12), but I'm not sure if that would be worse or better. :) 

Give it a try and let me know. Re-open this issue if you have further problems. :)

Thanks @osmarks!
