### ISSUE TITLE
How often does the DB update?

### ISSUE THREAD

**Issue by nmarshall23** [dizzyd/mcdex#17]
I've not seen any DB changes since I updated mcdex. I queried my mcdex.dat file no updates have been added to it. 

I even moved it and ran db.update, my new mcdex.dat, is the same size as the old.

**Comment by dizzyd** [comment]
Hi @nmarshall23! 

By default, mcdex updates once a day. I just released v0.8.3 that now displays what the most recent file is in the database so you can know how up to date it is.

Note that the crawler crashed a few days ago (my monitoring sucks), so it was not updating from Nov 1 - today. Should be all updated now, though. :)

I'm closing this ticket; but please let me know if you have any more problems.

**Comment by nmarshall23** [comment]
The Crawler has crashed again, last update in database was on 2017-12-07.

**Comment by dizzyd** [comment]
Hi @nmarshall23 - so it would appear my CoreOS doesn't restart my container/timer on reboot. Thanks for the heads up. I'm digging into it. In the meantime, I ran it by hand and it should be updated now.
