### ISSUE TITLE
[suggestion] Support some form of version pinning

### ISSUE THREAD

**Issue by miiichael** [dizzyd/mcdex#18]
Occasionally it's necessary to not use the latest version of a mod, or forge itself:
 - occasionally a forge update breaks a mod. Need to pin forge to specified release that doesn't break A (until that mod gets fixed).
 - mod updates sometimes introduce changes undesirable for existing servers.
 - other unspecified reasons :sweat_smile: 

It might suffice to provide the means to blacklist specific mod versions, and/or force a specific version for the mod.

It would also be nice to be able to exclude alpha and/or beta versions of mods (on a per-mod basis, as sometimes mods have only alpha/beta releases when you would otherwise ignore them).

**Comment by dizzyd** [comment]
Hi @miiichael!

As of 0.8.0, for any of the entry under "files" in manifest.json, you can add a "locked": true setting to stop mcdex from updating that entry when mod.update.all is run. This is a simple (yet effective) approach to version pinning. :)

Hope that helps!
