### ISSUE TITLE
[suggestion] Another Argument for Ignoring Failed Downloads

### ISSUE THREAD

**Issue by grim3212** [dizzyd/mcdex#22]
When downloading some older modpacks I have been unable to install them because of it exiting out once it comes to a 404.

I think another argument for ignoring these and continuing downloading would be useful.

**Comment by dizzyd** [comment]
Thanks @grim3212. I've added a new flag (--ignore) that will provide this functionality.

**Comment by dizzyd** [comment]
Fixed in v0.8.4.

**Comment by grim3212** [comment]
Thanks, looks great!
