### ISSUE TITLE
mcdex db.update not updating db

### ISSUE THREAD

**Issue by nmarshall23** [dizzyd/mcdex#23]
My db hasn't updated sense 2018-01-03

**Comment by dizzyd** [comment]
Hi @nmarshall23 - I just checked and it's still running; last update is 2018-01-05 17:04:39 -0700 MST?

Let me know if that's not true for you. :)

**Comment by nmarshall23** [comment]
It updated 9 days ago but has not updated sense.
Running db.update I get:

Database up-to-date as of 2018-01-09 18:52:31 -0500 EST

**Comment by dizzyd** [comment]
I hate systemctl. :/ DB is updating now again. I will investigate a more permanent solution tomorrow.

**Comment by dizzyd** [comment]
OK, I think I've finally got it setup correctly. Please reopen if it fails again.

**Comment by nmarshall23** [comment]
It's down again.

**Comment by dizzyd** [comment]
Fixed again. Different problem this time! :)

**Comment by dizzyd** [comment]
@nmarshall23 - FYI, I just released a new version that show elapsed time in easier to read format. :)
