### ISSUE TITLE
New profile not working on Windows

### ISSUE THREAD

**Issue by legomolina** [dizzyd/mcdex#24]
I've just downloaded the Windows version and installed a clean Minecraft (previously deleted C:\ProgramFiles(x86)\Minecraft folder and %appdata%\.minecraft). Once is installed I logged in and go to the cmd to execute the command and install the Age of Engineering modpack and all goes well but when I launch the game again, I have not any new profile created.

**Comment by GrenderG** [comment]
Same on Ubuntu 16.04.

**Comment by dizzyd** [comment]
Can you please try something for me?
1. Install Minecraft
2. Start Minecraft and Login
3. Shutdown Minecraft
4. Use mcdex to install the pack
5. Start Minecraft and Login

This _should_ work. Note that it's important to login into Minecraft at least once before running mcdex as Minecraft installs a bunch of files/configs that Mcdex requires. Let me know if that helps!

**Comment by legomolina** [comment]
Same as @GrenderG, downloaded and installed the game, run it, logged in successfully and executed the command to install the modpack.
All files were created under mods folder but not the profile.

**Comment by dizzyd** [comment]
Weird. I'll take a look this evening; could be that something changed in the launcher that I need to adjust for. :)

**Comment by GrenderG** [comment]
Thanks, keep us informed.

**Comment by dizzyd** [comment]
I've reproduced this. Working on a fix...

**Comment by dizzyd** [comment]
Fixed in v0.8.5. Thanks for the report!
