### ISSUE TITLE
[Suggesting] More flexable folder support

### ISSUE THREAD

**Issue by barcharcraz** [dizzyd/mcdex#29]
It would be nice to be able to develop modpacks (for example) in my multimc instance folder so I could launch them immediately

**Comment by dizzyd** [comment]
Can you describe the exact workflow you're looking for? We already have the ability to generate MMC config files -- I'm wondering what's missing. :)

**Comment by barcharcraz** [comment]
well for one it looks like the mmc config file support is broken (full report possibly incoming). I was looking for support for setting the pack directory to the mmc instances dir, so I could launch it directly with mmc.

My workflow now is
1) have pack managed my mmc
2) have same named pack managed by curse
3) junction the mod directories of the curse pack to the mmc pack
4) use curse to update mods.
