### ISSUE TITLE
Java folder missing

### ISSUE THREAD

**Issue by geekgarage** [dizzyd/mcdex#3]
`mcdex installPack "D:\Program Files (x86)\MultiMC\instances\Vanilla 1.10.2" https://minecraft.curseforge.com/projects/age-of-engineering/files/2446286`
CMD response: `2017/07/09 01:01:18 Failed to initialize: missing Java directory`

latest JRE is installed 32 and 64 bit

**Comment by dizzyd** [comment]
Hi @geekgarage - how did you install Java? This error only occurs when:
1. There is no JAVA_HOME set in your env
OR
2. There is no embedded Java installed with Minecraft
OR
3. Running "where java" fails

I've tried to cover all the variations I'm aware of, but noting that you're using MMC, I wonder if I missed something. :)

**Comment by geekgarage** [comment]
JRE was from the installers from Oracles website so nothing special about it.

According to what i can find JAVA_HOME is JDK specific and JRE is using JRE_HOME
I don't have JDK installed. Is this a must?

**Comment by geekgarage** [comment]
I've just uninstalled all JRE versions 8 build 91 and 8 build 131 both x86 and x64.
Then i reinstalled JDK x64 and added JAVA_HOME and JRE_HOME to env to their respective folders.
Minecraft is running fine both vanilla and MMC instances but mcdex is still throwing that error

**Comment by dizzyd** [comment]
Hm, ok this is very interesting. I've updated the latest build of mcdex w/ support for more verbose logging of the Java env. Can you please try running:

```mcdex -v info```

and send me the info via email (my github id @ my github id.com)

**Comment by geekgarage** [comment]
It mus have been me forgetting to restart to reload env references because now it works, but yes it seems like it is JDK depended so i think you should add that as a note to the instructions. I sent you a dump anyway if you can use it for some thing, and as a side note i had to manually add the ENV references (and restart)

**Comment by dizzyd** [comment]
Hi @geekgarage - glad we got it working! I just pushed up a new version of mcdex (0.6.3) that also checks for JRE_HOME. Hopefully that will avoid this problem in the future. :)

**Comment by geekgarage** [comment]
That is awesome, thanks for the update, i'll properly make a youtube video regarding my whole steam Link setup and how i use your program to update my mods :) Thank for a great program and hope you will keep it updated if the mod system ever change, because this save me TONS of work updating my mods
