### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by DbpGaming** [dizzyd/mcdex#31]
It seems that if you install a mod (example https://pastebin.com/6aBghrKd) not only are all required dependencies are downloaded, but all optional dependencies i don't know if this is intentional, but it makes it extremely hard to just install the mod you want

**Comment by dizzyd** [comment]
Fixed in 1f8d0ef03add8a443e8d4708924bcda368367eb7; will be part of the 0.9.1 release.
