### ISSUE TITLE
Mods Not Found

### ISSUE THREAD

**Issue by nmarshall23** [dizzyd/mcdex#33]
While building a modpack for 1.12.2, I found three mods that are not listed in mcdex's db.

[Cathedral](https://minecraft.curseforge.com/projects/cathedral)
[Earthworks](https://minecraft.curseforge.com/projects/earthworks)
[TIS-3D](https://minecraft.curseforge.com/projects/tis-3d)

I checked the `mcdex.dat ` file and I see they are not listed the mods table.

**Comment by dizzyd** [comment]
@nmarshall23 - I believe this has been resolved. Let me know if you see anything missing! :)
