### ISSUE TITLE
Commands should treat . as `pwd`

### ISSUE THREAD

**Issue by dizzyd** [dizzyd/mcdex#38]
When running a command that requires a directory, "." should be treated as if the user passed the absolute directory name.

**Comment by mgziminsky** [comment]
Doesn't it already do this?

https://github.com/dizzyd/mcdex/blob/91d9ddfc06e1349624121a477dd8f189c42fc85a/modpack.go#L67-L70

**Comment by dizzyd** [comment]
No, there was a subtle bug which I tracked down this morning. It worked for some cases, but not others -- should be consistent now :)
