### ISSUE TITLE
OptiFine Support

### ISSUE THREAD

**Issue by Quillan27** [dizzyd/mcdex#4]
It's up to you but I would love to see support for supplying a link from the OptiFine site.

**Comment by dizzyd** [comment]
Hi @Quillan27! 

I'll have to look into making OptiFine available in the database, but in the interim you can do:

```
mcdex mod.select 'http://optifine.net/adloadx?f=OptiFine_1.12_HD_U_C4.jar' optifine
```

That will add the Optifine JAR to your mod path when the pack is installed. :) Does that help any?

**Comment by dizzyd** [comment]
Actually, that doesn't work, since all the OptiFine JARs are behind ad-paywalls. :/ If there are legal links to the OptiFine mods, I'd be happy to add them.

**Comment by Quillan27** [comment]
What about "http://optifine.net/downloadx?f=OptiFine_1.12_HD_U_C4.jar&x=ba49eaf795f7cfa2279f2e24342274b7"
This is the link I copied from the download button after the adds page

**Comment by dizzyd** [comment]
@Quillan27 - while that would work, I feel uncomfortable with trying to deliberately bypass their ad-wall without permission. I've emailed the Optifine team to see if we can find some middle ground. Will let you know what happens. :)

**Comment by dizzyd** [comment]
@Quillan27 - I haven't recv'd a response from Optifine, so I'm going to assume they wouldn't be ok with including their JAR files without the ad-wall. 

If you can get them to grant permission (via a post on this ticket or to my email address), I can easily add the code. :) Otherwise, closing this ticket.
