### ISSUE TITLE
Failed to download: too many colons in address

### ISSUE THREAD

**Issue by rohit507** [dizzyd/mcdex#43]
I've built mcdex-0.9.5 on ubuntu w/ the current go snap (installed via `sudo snap install go --classic`) and have the following error when trying to download any modpack: 

```
$> mcdex pack.install aoe age-of-engineering
-- /home/<usr>/.minecraft/mcdex/pack/aoe --
Starting download of modpack: https://minecraft.curseforge.com/projects/263897/files/2503175/download
2019/03/02 09:53:36 Failed to download aoe: Get https://minecraft.curseforge.com/projects/263897/files/2503175/download: dial tcp: address 2606:4700::6813:9284:443: too many colons in address
```

It's unclear whether you mean for it to be using ipv6.

**Comment by osmarks** [comment]
I'm experiencing this too.

**Comment by dizzyd** [comment]
Can you please run:

ping minecraft.curseforge.com

and let me know what you get back? There's no specific IPv4/6 code in mcdex and I just validated it works on a fresh Ubuntu install. My suspicion is that this is your network configuration, but that ping should tell us more. :)

**Comment by osmarks** [comment]
I added `104.19.146.132          minecraft.curseforge.com` to `/etc/hosts` and it downloads fine; here's the ping output.
```
ping minecraft.curseforge.com
PING minecraft.curseforge.com (104.19.146.132) 56(84) bytes of data.
64 bytes from minecraft.curseforge.com (104.19.146.132): icmp_seq=1 ttl=57 time=16.10 ms
64 bytes from minecraft.curseforge.com (104.19.146.132): icmp_seq=2 ttl=57 time=19.1 ms
```

Without that, it's this:
```
ping minecraft.curseforge.com
PING minecraft.curseforge.com(2606:4700::6813:9284 (2606:4700::6813:9284)) 56 data bytes
64 bytes from 2606:4700::6813:9284 (2606:4700::6813:9284): icmp_seq=1 ttl=57 time=67.0 ms
64 bytes from 2606:4700::6813:9284 (2606:4700::6813:9284): icmp_seq=2 ttl=57 time=22.1 ms
```

**Comment by dizzyd** [comment]
@osmarks I just had a PR submitted that resolved this issue. I'll be cutting a new release later today with this change incorporated. :)
