### ISSUE TITLE
Install from manifest.json

### ISSUE THREAD

**Issue by osmarks** [dizzyd/mcdex#44]
I'd like to distribute a pack without going through curseforge, via publishing the `manifest.json` on Github. Currently, this requires creating a new pack, replacing the default `manifest.json` with mine, and then installing that. It would be convenient to be able to just run a single command, perhaps `mcdex pack.install.from_manifest` to create and install a pack from a manifest.

**Comment by dizzyd** [comment]
I'm a little confused, but maybe I'm missing part of the workflow. To create a new modpack, I usually do something like:

mkdir mypack; cd mypack
mcdex pack.create . 1.12.2 # Creates an empty manifest with stable forge
mcdex mod.select .... # Get all my mods

Does this not work for some reason?

**Comment by osmarks** [comment]
Nope. I get 
```
Creating profile: .
2019/03/03 20:26:45 failed to create profile: invalid profile name: .
```

**Comment by dizzyd** [comment]
@osmarks try using the latest build (0.9.6+). There were some bugs in the relative directory handling in prior versions. Please feel free to re-open if it's still a problem. :)
