### ISSUE TITLE
running on linux (I'm probably being stupid)

### ISSUE THREAD

**Issue by deep-fried-bacon** [dizzyd/mcdex#45]
I'm having issues running this on linux.
How are you supposed to run it? Do I need to install it somehow?

**Comment by dizzyd** [comment]
Hi @deep-fried-bacon - you need to download the [Linux](http://files.mcdex.net/releases/linux/mcdex) executable from the link in the README. Once that's downloaded, you just need to make sure it's executable or on your PATH and it should Just Work (tm). Please feel free to re-open if that's not fixing it. :)
