### ISSUE TITLE
mcdex doesn't support the new forge site.

### ISSUE THREAD

**Issue by Develon5543** [dizzyd/mcdex#49]
This tool explicitly checks for minecraft.curseforge.com now, but the new url is just curseforge.com. This means it's impossible to download modpacks from Curse now.

**Comment by Develon5543** [comment]
Also, even if I comment out the checks in modpack.go, the individual mods fail to download because of the new URL scheme.

**Comment by Develon5543** [comment]
Also also, I can't figure out how to download a file just by its file ID and project ID. It looks like we need the mod names now? There's also a curse API that might be of help, but that's java-based. I just can't seem to assemble a valid URL that produces a zip file and not an html file using just the numbers..

**Comment by Develon5543** [comment]
I found out the new link format for you to incorporate into your program.
Modpack URL: https://www.curseforge.com/minecraft/modpacks/projectID/download/fileID/file
Mod URL: https://curseforge.com/minecraft/mc-mods/projectID/download/fileID/file

**Comment by Bockiii** [comment]
Hi,

I can see that you made the commits, but the released linux version still has the issue. Do you need to kick off the build for that?

**Comment by Bockiii** [comment]
Is it possible that you missed a spot in the db.go?

```
// Construct a URL using the slug and file ID
	return fmt.Sprintf("https://minecraft.curseforge.com/projects/%d/files/%d/download", pid, fileID), nil;

```

**Comment by Develon5543** [comment]
Ah, I'm not the one who did a pull request or any commits. I simply changed the code locally and used it that way. Sorry about that.

**Comment by Bockiii** [comment]
I meant @dizzyd :) I just hijacked your issue because it was the latest about curseforge not working :)

**Comment by dizzyd** [comment]
So, my git got messed up -- which is _part_ of the problem. There is another problem that I'm still working through. Hope to have it fixed today. :/

**Comment by dizzyd** [comment]
Ok, 0.9.7 is out that fixes all these problems. Let me know if it breaks again!

**Comment by gamer4life1** [comment]
I have the same issue with macos
#53
