### ISSUE TITLE
mcdex db.update failing

### ISSUE THREAD

**Issue by geekgarage** [dizzyd/mcdex#5]
```
D:\mcdex>mcdex db.update
2017/07/25 16:13:21 Failed to rename mcdex.dat.tmp: rename C:\Users\rasmu\AppData\Roaming\.minecraft\mcdex\mcdex.dat.tmp C:\Users\rasmu\AppData\Roaming\.minecraft\mcdex\mcdex.dat: The process cannot access the file as it is in use by another process 
```

(Process part translated by me from danish)

same setup where we left it last time :) JDK x64 Server running fine. I can manually change the file from mcdex.dat.tmp to mcdex.dat when i click the permission confirmation as i'm working on C drive en %appdata% (Windows 10 pro x64)

All this is tried with Minecraft client and server shut down.

What i'm trying do do is use it to install extra mods into a modpack, that is also installed with mcdex, and then i saw the list command and wanted to try it out.

some debug info:
```
Version: v0.7.0-0-g86e2d10
Env: {MinecraftDir:C:\Users\rasmu\AppData\Roaming\.minecraft McdexDir:C:\Users\rasmu\AppData\Roaming\.minecraft\mcdex JavaDir:C:\Program Files\Java\jdk1.8.0_131}
```

**Comment by dizzyd** [comment]
Fixed in 336bd3e; update to latest mcdex (v0.7.1) and it should be good to go.
