### ISSUE TITLE
***SUGGESTION*** Modpack/mod download link

### ISSUE THREAD

**Issue by geekgarage** [dizzyd/mcdex#6]
Would it be possible to add a function so you can supply **pack.install** with a link and version and then it grabs the latest pack of the modpack or mod for that MC version?

Like AoE just updated to 1.0.4 so to update it today i need to call MCdex with a new full link to the file like this just to update:
`mcdex pack.install aoe https://minecraft.curseforge.com/projects/age-of-engineering/files/2455050`

Instead it would be nice to have it like this or also supporting

`mcdex pack.install aoe https://minecraft.curseforge.com/projects/age-of-engineering/files 1.10.2`

This way i would be able to create a shortcut that will grab the latest version of the linked modpack and i can do an easy upgrade of the server :)
this would also be nice to have available for **mod.select** and **mod.select.client**
Curse have the uploaded date and version shown.

I know your tool have been created for modpack creation in mind, but with this implemented it will also be an awesome management tool.

**Comment by dizzyd** [comment]
@geekgarage - I've been investigating this. I'd like to add it, but it's going to take some time to rework everything.

**Comment by geekgarage** [comment]
I'm absolutely for it and I can wait, also why I marked it as suggestion.

**Comment by dizzyd** [comment]
@geekgarage - 0.9.5 now supports installing modpacks based on slug name. Thus you can do:

mcdex pack.install age-of-engineering

and it will find the latest one available and install it.
