### ISSUE TITLE
Full path fails install

### ISSUE THREAD

**Issue by geekgarage** [dizzyd/mcdex#7]
I'm in the process of moving the folder to another location and drive and testing the pack.install with just a name works flawless, BUT, adding a full path doesn't as it appends the path to the .minecraft path

So using the command:
`D:\mcdex>mcdex pack.install D:\mcdex\servers\aoe https://minecraft.curseforge.com/projects/age-of-engineering/files/2455050`

Returns:
`-- C:\Users\rasmu\AppData\Roaming\.minecraft\mcdex\pack\D:\mcdex\servers\aoe --
2017/07/25 18:04:09 Failed to create C:\Users\rasmu\AppData\Roaming\.minecraft\mcdex\pack\D:\mcdex\servers\aoe: mkdir C:\Users\rasmu\AppData\Roaming\.minecraft\mcdex\pack\D:: Syntax in file, folder or volume is incorrect.`

And as you can see it just appends D:\mcdex\servers\aoe to C:\Users\rasmu\AppData\Roaming\.minecraft\mcdex\pack\

**Comment by dizzyd** [comment]
Fixed in f3d9517.

**Comment by dizzyd** [comment]
Fixed in f3d9517
