### ISSUE TITLE
Profile not created if its name contains a dash

### ISSUE THREAD

**Issue by adl** [dizzyd/mcdex#8]
The following command
```
mcdex pack.install farming-valley https://minecraft.curseforge.com/projects/farming-valley/files/2451700
```
displays `Creating profile: farming-valley`, but the profile is not created, and no error is printed.

Running the same command with `farmingvalley` without the dash works.

**Comment by dizzyd** [comment]
Hi @adl, thanks for reporting this. There were a few problems in play, all of which are now corrected. mcdex was being unnecessarily strict on the names and then it also wasn't properly reporting when the name check failed. 

I've published v0.7.2 with these fixes. Please let me know if you encounter any additional problems.
