### ISSUE TITLE
Does mcdex check for changed files?

### ISSUE THREAD

**Issue by Eufranio** [dizzyd/mcdex#9]
Some files, like text files, can change and be different from the ones of the original pack. What's the mcdex behaviour of when this happens?

**Comment by dizzyd** [comment]
Hi @Eufranio - if you install a pack, modify the files and then install the pack again, the changes will be lost. Is that the use case you're describing? What behaviour would you like to see?

**Comment by Eufranio** [comment]
I had an modpack installed, it updated, and when I updated my pack via mcdex, the new mods were NOT downloaded, I had to download them manually and updated. I'm not sure why this happened, so I thought it was something mcdex was doing with modified files or so...

**Comment by dizzyd** [comment]
Can you list the specific mcdex commands you ran, and the order in which you ran them, please? Sounds like a bug that I need to reproduce.

**Comment by Eufranio** [comment]
For the first time, as root, I ran `./mcdex db.update`, then `./mcdex pack.install /path/to/pack/ https://minecraft.curseforge.com/projects/age-of-engineering/`. When I first installed, the latest version was 1.0.4, so it installed the 1.0.4 version correctly. Now, it updated to 1.0.5 and I ran those same commands, but now the new mods were NOT installed.

**Comment by dizzyd** [comment]
Hi @Eufranio - I've narrowed down the problem but need to think about the best way to fix it. Right now, mcdex will not re-download a pack when it finds an existing pack file (pack.zip) already on disk. Thus, the manifest doesn't get updated and the pack mods don't change.

I'll have a fix for you in a day or so. :)

**Comment by dizzyd** [comment]
Hi @Eufranio - well, that was easier than expected. Grab v0.7.3 and it will now do the right thing when you update packs. :)
